apps/device/urls.py
# Author Cuber
# coding=utf-8
# @Time    : 2021/2/2 17:37
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

apps/website/urls.py
# Author Cuber
# coding=utf-8
# @Time    : 2021/2/2 11:43
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

from django.urls import path, include
from django.conf.urls import url
from apps.website import views as webViews
from apps.workers import views as userViews

app_name = 'website'  # 指定应用名，在使用{% url ' ' %} 引用链接时就可以套用对应应用名下的模板
urlpatterns = [
    url(r'login', userViews.Login.as_view(), name='login'),  # 登陆验证
    url(r'logout', userViews.Logout, name='logout'),
    url(r'register', userViews.Register.as_view(), name='register'),  # 登陆验证
    # url(r'^dashboard$', webViews.Dashboard.as_view()),  # 登陆验证
    # url(r'^charts$', webViews.Chart.as_view()),  # 登陆验证
    # url(r'^devices', webViews.Device.as_view()),  # 登陆验证
    # url(r'^streams', webViews.Stream.as_view()),  # 登陆验证
    # url(r'^console', webViews.Console.as_view()),  # 登陆验证
    # url(r'^triggers', webViews.Trigger.as_view()),  # 登陆验证
]

apps/workers/urls.py
# Author Cuber
# coding=utf-8
# @Time    : 2021/2/2 17:37
# @Site    : 
# @File    : urls.py
# @Software: PyCharm

emqWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', TemplateView.as_view(template_name="home.html"), name='homepage'),
    path(r'', include('apps.website.urls', namespace='website')),
    # path(r'/devices', include('device.urls', namespace='device')),
    # path(r'/workers', include('workers.urls', namespace='workers'))
]

apps/device/models.py
from django.db import models
from apps.website.models import DataStream


class Info(models.Model):
    # 在前端可通过点击数据浏览标签进入该设备的实时展 示
    device_id = models.IntegerField(primary_key=True, unique=True, null=False)  # 设备号为主键
    tag = models.CharField(max_length=32, null=True, blank=True)  # 设备标签-设备类型
    device_key = models.CharField(max_length=32, null=True, blank=True)  # 设备传输密钥
    device_name = models.CharField(max_length=32, null=True, blank=True)  # 设备名S
    dev_status = models.BooleanField(default=0, null=False)  # 在线状态,默认为 0 present offset and 1 present online
    creative_date = models.DateTimeField(auto_now_add=True)  # 创建时间
    protocol = models.CharField(max_length=10, null=True, default='mqtt')  # 传输协议,默认使用mqtt协议
    # 数据流为json序列，主要内容为所采集数据，这部分为每个设备的数据集的外键，多对多关系
    dev_stream = models.ManyToManyField(DataStream, blank=True, null=True)  # 传感器数据流

    class Meta:
        db_table = 'deviceInfo'

apps/website/models.py
from django.db import models


# 思考，数据由mqtt消息中间件转发得到的数据时string类型，
# we need jsonStr to be parsed into json


class Data(models.Model):
    data = models.CharField(max_length=64, null=True, blank=True)  # 限制在两位小数
    date = models.DateTimeField(auto_now_add=True)  # 上传时间,自动保存时间

    class Meta:
        db_table = 'DataList'


class DataStream(models.Model):
    stream_name = models.CharField(max_length=20, null=False)  # 数据流名称如'温度'，'湿度'
    stream_para = models.IntegerField(null=True, default=0)  # 数据类型,以属性代码表示0-4分别表示温度、湿度、甲烷浓度等数据流属性
    limit = models.FloatField(null=True, default=0, blank=True)  # 阈值数值,此变量受神经网络算法部分影响,可修改
    qos = models.IntegerField(null=True, default=0)  # 服务质量,0-2
    unit = models.CharField(max_length=10, null=True, blank=True)  # 单位名称,如'米'
    unit_symbol = models.CharField(max_length=10, null=True, blank=True)  # 单位符号,如'm'
    data = models.ManyToManyField(Data, null=True, blank=True)

    class Meta:
        db_table = 'StreamList'

apps/workers/models.py
from django.utils import timezone

from apps.device.models import Info
from django.db import models
from django.contrib.auth.models import AbstractUser


class GUser(AbstractUser):
    # 对User模型的自定义以及拓展,定义一个工人模型即工人数据信息表
    # 工人基本信息，固定,与User模型对应并在此基础上拓展
    workerId = models.IntegerField(unique=True, db_index=True, blank=True, null=True)  # 工号由后端生成
    # 后续可修改的信息
    sex = models.BooleanField(null=True, default=0)  # 性别 0 represent male and 1 represent female
    tel = models.CharField(max_length=20, blank=True, null=True)  # 联系方式
    # 通勤时间，上下班打卡记录自动写入当前时间,时间的修改因受到员工签到事件的触发
    commute_start = models.DateTimeField(default=timezone.now, blank=True)
    commute_end = models.DateTimeField(default=timezone.now, blank=True)
    # 绑定设备,一对多关系，一个员工对应多个设备
    device = models.ForeignKey(Info, on_delete=models.CASCADE, blank=True, null=True)
    # 岗位类型，如矿井工人，地上检查员，基站管理员等，后续通过代码号进行分类
    post = models.IntegerField(blank=True, db_index=True, default=0)

    class Meta(AbstractUser.Meta):
        # 该U属性值定义模型对应的数据表名词
        db_table = 'userInfo'

    def __str__(self):
        return self.username

apps/website/forms.py
# Author Cuber
# coding=utf-8
# @Time    : 2021/2/5 19:44
# @Site    : 
# @File    : forms.py
# @Software: PyCharm

apps/workers/forms.py
# Author Cuber
# coding=utf-8
# @Time    : 2021/2/6 16:43
# @Site    : 
# @File    : forms.py
# @Software: PyCharm


from django import forms

from .models import GUser


# 对于与用户而非管理的这类对象，不需要对数据库进行交互改动的，通过集成forms.Form来自行配置字段信息
# 对于管理员则通过继承forms.ModelForm

# 登录表单
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 注册表单
class UserRegisterForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()
    password2 = forms.CharField()

    # 定义校验方法
    def clean_password(self):
        # 校验密码的合法性，不能为纯数据
        password = self.cleaned_data.get("password")
        if password.isdecimal():
            raise forms.ValidationError("密码不能为纯数字！")
        return password

    def clean_r_password(self):
        # 校验密码的合法性，不能为纯数据
        r_password = self.cleaned_data.get("password2")
        if r_password.isdecimal():
            raise forms.ValidationError("密码不能为纯数字！")
        return r_password

    # 定义全局钩子
    def clean(self):
        # 校验两次密码输入是否一致
        if self.cleaned_data.get("password") != self.cleaned_data.get("password2"):
            self.add_error("password2", "两次密码输入不一致！")
        else:
            return self.cleaned_data

apps/device/views.py
from django.shortcuts import render

# Create your views here.

apps/website/views.py
# 对数据处理的功能函数
# 全局检索

apps/workers/views.py
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
# from django.shortcuts import render, HttpResponse
from rest_framework.utils import json
from rest_framework.views import APIView
from rest_framework.parsers import JSONParser, FormParser
from . import database, models

from .forms import UserLoginForm, UserRegisterForm


# JSonResponse 前端不用反序列化，只能传输字典，不能传输字符串。


# 登录操作
class Login(APIView):
    parser_classes = [JSONParser, FormParser]  # 指定数据解析器
    authentication_classes = []

    def post(self, request):
        # username = request.data.get('username', None)
        # password = request.data.get('password', None)
        user_login_form = UserLoginForm(data=request.POST)

        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据,返回对应模型统一格式的字段
            data = user_login_form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 将用户数据保存在 session 中，即实现了登录动作并且保持的是非永久登录状态直至网页关闭
                login(request, user)
                return redirect("homepage")
            else:
                return HttpResponse("账号或密码输入有误。请重新输入~")
        else:
            return HttpResponse("账号或密码输入不合法")

    def get(self, request):
        return render(request, 'website/login.html')


# 登出操作
def Logout(request):
    logout(request)
    return redirect('homepage')


# 注册用户
class Register(APIView):
    # 以下通过直接截取POST的数据的方法实现注册
    def post(self, request):
        username = request.data.get('username', None)
        password = request.data.get('password', None)
        password2 = request.data.get('password2', None)
        res = database.register(username, password, password2)
        if res['message'] == 'Succeed':
            # 注册成功则直接跳转至主页并维持登录状态
            user = models.GUser.objects.filter(username=username).first()
            login(request, user)
            return redirect('homepage')
        # 注册失败返回错误提示
        return HttpResponse(json.dumps(res, ensure_ascii=False), content_type='application/json', )

    def get(self, request):
        return render(request, 'website/register.html')

templates/base.html
<!DOCTYPE html>

<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    {#    <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
    <meta http-equiv="Content-Type" content="text/html"/>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.1/dist/css/bootstrap.min.css"
          rel="stylesheet">

    <!-- CSS only -->
    <link type="text/css" rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css">

    <!-- JS, Popper.js, and jQuery -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"
            rel="stylesheet"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            rel="stylesheet"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.1/dist/js/bootstrap.min.js"
            rel="stylesheet"></script>


    {% block link %}{% endblock %}
    {#    {% load_tctip %}#}
</head>
<body>

<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
{% block content %}
{% endblock content %}
<!-- 引入注脚 -->
{% include 'footer.html' %}

{% block script %}{% endblock script %}
</body>
</html>

templates/footer.html
{% load static %}
<!-- Footer -->
<nav class="navbar fixed-bottom navbar-light bg-light">
  <a class="navbar-brand" href="#">footer information</a>
</nav>

templates/header.html
{% load static %}
<!-- 定义导航 site_logo-->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-4">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Device</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            {% if user.is_authenticated %}
                <!-- 如果用户已经登录，则显示用户名下拉框 -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'website:logout' %}">退出登录</a>
                    </div>
                </li>
                <!-- 如果用户未登录，则显示 “登录” -->
            {% else %}
                <li class="nav-item ml-4">
                    <a class="nav-link" href="{% url 'website:login' %}">登录</a>
                </li>
                <!-- if 语句在这里结束 -->
            {% endif %}
        </ul>
    </div>
</nav>

templates/home.html
{% extends "base.html" %} {% load static %}

{% block title %} 平台首页{% endblock title %}
{% block link %}
{% endblock %}

{% block content %}
 <div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
</div>
{% endblock content %}

templates/website/login.html
{% extends "base.html" %}
{% block title %} 登录 {% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action="login.html">
                    {% csrf_token %}
                    <!-- 账号 -->
                    <div class="form-group col-md-4">
                        <label for="username">用户名</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>

                    <!-- 密码 -->
                    <div class="form-group col-md-4">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
                <a class="btn btn-secondary mt-2" href="{% url 'website:register' %}" role="button">若没有账号，请注册</a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/website/register.html
{% extends "base.html" %}
{% block title %} 登录 {% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action="{% url 'website:register' %}" >
                    {% csrf_token %}
                    <!-- 账号 -->
                    <div class="form-group col-md-4">
                        <label for="username">用户名</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <!-- 密码 -->
                    <div class="form-group col-md-4">
                        <label for="password">设置密码</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    <!-- 确认密码 -->
                    <div class="form-group col-md-4">
                        <label for="password2">确认密码</label>
                        <input type="password" class="form-control" id="password2" name="password2" required>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">注册</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}